### ISSUE TITLE
Move the source files from PDFs to actual .java files

### ISSUE THREAD

**Issue by 2DSharp** [IdealisticINTJ/Data-Structures-and-Algorithms-in-Java#1]
PDFs are hard to access and edit. Put your source code in Java files and commit them. This way someone else can benefit from them or contribute to them as well! :)

For reference, I made this in my early years at college: https://github.com/2DSharp/college

**Comment by salma2vec** [comment]
Hey there, @2DSharp - Thanks for opening this issue!
I'll take that into consideration. 
P.S: I apologize for the delayed response.
